swagger: "2.0"
info:
  title: api
  description: "API Gateway"
  version: "1.0"
basePath: api
schemes:
  - "https"
tags:
  - name: hello-world-controller
    description: Hello World Controller
paths:
  "/hello/world":
    get:
      tags:
        - hello-world-controller
      summary: getHelloWorld
      operationId: getHelloWorldUsingGET
      produces:
        - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: "when_no_match"
        type: "mock"
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "200":
          description: OK
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "200"
        requestTemplates:
          application/json: '{"statusCode": 200}'
        passthroughBehavior: "when_no_match"
        type: "mock"
x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:
    responseParameters:
      gatewayresponse.header.Access-Control-Allow-Methods: "'DELETE,GET,OPTIONS,POST,PUT'"
      gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
      gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
