stages:
  - init-to-plan
  - apply
  - init-to-destroy
  - destroy

image:
    name: hashicorp/terraform
    entrypoint:
        - "/usr/bin/env"
        - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

############################
########### PLAN ###########
############################

.init-to-plan:
    stage: init-to-plan
    before_script:
        - terraform --version
        - terraform init -backend-config=${TFVARS_PATH}_backend.tf
        - terraform validate
    script:
        - terraform plan --var-file="${TFVARS_PATH}.tfvars" -out "terraform.plan"
    artifacts:
        paths:
            - .terraform
            - terraform.plan
            - .terraform.lock.hcl

init-to-plan-dev:
    variables:
        TFVARS_PATH: env/dev
    extends:
        - .init-to-plan
    environment: dev

init-to-plan-prod:
    variables:
        TFVARS_PATH: env/prod
    extends:
        - .init-to-plan
    environment: prod

#############################
########### APPLY ###########
#############################

.apply:
    stage: apply
    before_script:
        - terraform --version
    script:
        - terraform apply "terraform.plan"
    when: manual
    timeout: 6h
    artifacts:
        paths:
            - .terraform
            - terraform.plan
            - .terraform.lock.hcl

apply-env:
    extends:
        - .apply
    environment: env

apply-prod:
    extends:
        - .apply
    environment: prod

####################################
########### PLAN DESTROY ###########
####################################

.init-to-destroy:
    stage: init-to-destroy
    before_script:
        - terraform --version
        - terraform validate
    script:
        - terraform plan -destroy -var-file="${TFVARS_PATH}.tfvars" -out "terraform.plan"
    when: manual
    timeout: 2h
    artifacts:
        paths:
            - .terraform
            - terraform.plan
            - .terraform.lock.hcl

init-to-destroy-dev:
    variables:
        TFVARS_PATH: env/dev
    extends:
        - .init-to-destroy
    environment: dev
    dependencies:
        - init-to-plan-dev

init-to-destroy-prod:
    variables:
        TFVARS_PATH: env/prod
    extends:
        - .init-to-destroy
    environment: prod
    dependencies:
        - init-to-plan-prod

###############################
########### DESTROY ###########
###############################

.destroy:
    stage: destroy
    before_script:
        - terraform --version
    script:
        - terraform apply "terraform.plan"
    when: manual
    timeout: 24h
    artifacts:
        paths:
            - .terraform
            - terraform.plan
            - .terraform.lock.hcl

destroy-dev:
    extends:
        - .destroy
    environment: dev

destroy-prod:
    extends:
        - .destroy
    environment: prod